"""add portal and question

Revision ID: 1de1af862e18
Revises: 625c6c4b64fb
Create Date: 2022-04-14 00:50:42.758246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1de1af862e18'
down_revision = '625c6c4b64fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pat_id', sa.Integer(), nullable=True),
    sa.Column('doc_id', sa.Integer(), nullable=True),
    sa.Column('patientname', sa.String(length=80), nullable=True),
    sa.Column('pdfname', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['pat_id'], ['patientsusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('age', sa.String(length=80), nullable=True),
    sa.Column('gender', sa.String(length=80), nullable=True),
    sa.Column('diet', sa.String(length=80), nullable=True),
    sa.Column('smoking', sa.String(length=80), nullable=True),
    sa.Column('alcohol', sa.String(length=80), nullable=True),
    sa.Column('medication', sa.String(length=80), nullable=True),
    sa.Column('dieases', sa.String(length=80), nullable=True),
    sa.Column('complaints', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['patientsusers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('portal')
    # ### end Alembic commands ###
