"""add img_link in Posts

Revision ID: 443bda6a691c
Revises: be5fc7757135
Create Date: 2022-03-15 15:45:00.021263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443bda6a691c'
down_revision = 'be5fc7757135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('img_link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'img_link')
    # ### end Alembic commands ###
