"""add title field

Revision ID: 80197fbc6165
Revises: 443bda6a691c
Create Date: 2022-03-16 15:54:31.289472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80197fbc6165'
down_revision = '443bda6a691c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    # ### end Alembic commands ###
