"""add tables and foreign key

Revision ID: be5fc7757135
Revises: 
Create Date: 2022-03-14 22:00:57.586344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be5fc7757135'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('PDF__extracter', sa.Column('visits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('PDF__extracter', 'visits')
    # ### end Alembic commands ###
